# Generated by Django 3.2.4 on 2022-08-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='msgDate',
        ),
    ]
