# Generated by Django 3.2.4 on 2022-08-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_inbox_msgdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='mailBody',
            field=models.CharField(max_length=1000),
        ),
    ]
