# Generated by Django 3.2.4 on 2022-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_inbox_mailbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='mailBody',
            field=models.TextField(),
        ),
    ]
