# Generated by Django 3.2.4 on 2022-08-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_forgetuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
